controller_joint_names: ['', '13_Joint', '12_Joint', '11_Joint', '23_Joint', '22_Joint', '21_Joint', '33_Joint', '32_Joint', '31_Joint', '43_Joint', '42_Joint', '41_Joint', '53_Joint', '52_Joint', '51_Joint', '50_Joint', '500_Joint', ]
